# Model arguments
model_name_or_path: ../llm_models/Qwen2.5-3B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: DigitalLearningGmbH/MATH-lighteval #../llm_datasets/MATH-lighteval #
# dataset_configs:
# - default
system_prompt: "You are a helpful AI Assistant that provides well-reasoned and detailed responses. You first think about the reasoning process as an internal monologue and then provide the user with the answer. Respond in the following format: <think>\n...\n</think>\n<answer>\n...\n</answer>"

# GRPO trainer config
bf16: true
use_vllm: true
# vllm_device: auto
# vllm_gpu_memory_utilization: 0.7
do_eval: false
gradient_accumulation_steps: 32 #4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: Qwen2.5-3B-Instruct-OpenR1-GRPO
hub_strategy: every_save
learning_rate: 5.0e-06
log_completions: true
log_level: info
logging_first_step: true
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine
max_prompt_length: 1024
max_completion_length: 2048
max_steps: -1
num_generations: 6
num_train_epochs: 1
output_dir: output_models/fedgrpo/Qwen2.5-3B-Instruct-mathlight-fedgrpo-len-0706-2048-lr5e6
overwrite_output_dir: true
per_device_eval_batch_size: 6 #16
per_device_train_batch_size: 6 #16
push_to_hub: false
report_to:
- wandb
reward_funcs:
- accuracy
- format
- length
# - tag_count
reward_weights:
- 1.0
- 0.1
- 1.0
save_strategy: "epoch"
save_total_limit: 1
seed: 42
warmup_ratio: 0.1
